version: '3.8'

services:
  app:
    image: your-java-app-image:latest
    container_name: java_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
